-- ============================================================
-- CREATAI :: V1 schema
-- Run this once in your Supabase SQL Editor.
-- ============================================================

create extension if not exists pgcrypto;

-- ============================================================
-- BRANDS — one user can have many brand profiles
-- ============================================================
create table if not exists public.brands (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  tagline text,
  mission text,
  audience text,
  tone text,
  products text,
  usps text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ============================================================
-- WATCHLIST :: COMPETITORS
-- ============================================================
create table if not exists public.competitors (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users(id) on delete cascade,
  brand_id uuid references public.brands(id) on delete cascade,
  name text not null,
  platform text,
  handle_or_url text,
  category text,
  notes text,
  created_at timestamptz not null default now()
);

-- ============================================================
-- WATCHLIST :: CREATORS
-- ============================================================
create table if not exists public.creators (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users(id) on delete cascade,
  brand_id uuid references public.brands(id) on delete cascade,
  name text not null,
  platform text,
  handle_or_url text,
  niche text,
  notes text,
  created_at timestamptz not null default now()
);

-- ============================================================
-- CONTENT ASSETS — every analyzed piece of content
-- ============================================================
create table if not exists public.content_assets (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users(id) on delete cascade,
  brand_id uuid references public.brands(id) on delete set null,

  -- source
  source_url text,
  platform text,                  -- instagram | tiktok | youtube | linkedin | meta_ad | other
  content_type text,              -- video | image | carousel | story | ad

  -- linked entities (optional)
  creator_id uuid references public.creators(id) on delete set null,
  competitor_id uuid references public.competitors(id) on delete set null,

  -- display metadata
  title text,
  campaign_name text,
  creator_name text,              -- denormalized for fast display
  competitor_name text,

  -- raw inputs
  caption text,
  transcript text,
  thumbnail_url text,             -- storage path or external URL

  -- manual metrics
  views integer,
  likes integer,
  comments integer,
  shares integer,
  saves integer,
  spend numeric,
  conversions integer,
  notes text,

  -- extraction metadata
  extraction_status text default 'pending',     -- pending | extracted | failed | manual
  extraction_source text,                        -- youtube | vision | whisper | manual
  extracted_at timestamptz,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ============================================================
-- CREATIVE DNA REPORTS — one per asset, generated by LLM
-- ============================================================
create table if not exists public.creative_dna_reports (
  id uuid primary key default gen_random_uuid(),
  asset_id uuid not null unique references public.content_assets(id) on delete cascade,
  owner_id uuid not null references auth.users(id) on delete cascade,

  -- 15 categorical attributes
  hook_style text,
  content_type text,
  format text,
  tone text,
  emotion text,
  visual_style text,
  cta_quality text,
  content_territory text,
  audience_stage text,
  product_role text,
  psychological_trigger text,
  brand_presence text,
  creator_presence text,
  storytelling_structure text,
  creative_family text,

  -- 6 scores (0-100)
  predicted_performance_score integer,
  hook_score integer,
  retention_score integer,
  engagement_score integer,
  conversion_score integer,
  novelty_score integer,

  -- narrative analysis
  what_is_working text,
  what_is_weak text,
  what_to_improve text,
  content_ideas jsonb,        -- ["idea1", "idea2", ...]

  -- meta
  model text default 'gpt-4o',
  raw_response jsonb,
  created_at timestamptz not null default now()
);

-- ============================================================
-- CREATIVE CLUSTERS — LLM-grouped families of assets
-- ============================================================
create table if not exists public.creative_clusters (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users(id) on delete cascade,
  brand_id uuid references public.brands(id) on delete cascade,
  name text not null,
  description text,
  common_hook_style text,
  common_emotion text,
  common_territory text,
  avg_performance_score numeric,
  asset_count integer default 0,
  why_it_matters text,
  recommended_next_move text,
  asset_ids uuid[] default '{}'::uuid[],
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ============================================================
-- AI CHAT MESSAGES — AI Analyst transcript
-- ============================================================
create table if not exists public.ai_chat_messages (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users(id) on delete cascade,
  brand_id uuid references public.brands(id) on delete cascade,
  thread_id uuid not null,
  role text not null,                  -- user | assistant | system
  content text not null,
  citations jsonb,                     -- [{asset_id, title}, ...]
  model text,
  created_at timestamptz not null default now()
);

-- ============================================================
-- INDEXES
-- ============================================================
create index if not exists brands_owner_idx           on public.brands(owner_id);
create index if not exists competitors_owner_idx      on public.competitors(owner_id);
create index if not exists creators_owner_idx         on public.creators(owner_id);
create index if not exists assets_owner_idx           on public.content_assets(owner_id);
create index if not exists assets_brand_idx           on public.content_assets(brand_id);
create index if not exists assets_platform_idx        on public.content_assets(platform);
create index if not exists assets_created_idx         on public.content_assets(created_at desc);
create index if not exists dna_owner_idx              on public.creative_dna_reports(owner_id);
create index if not exists dna_family_idx             on public.creative_dna_reports(creative_family);
create index if not exists clusters_owner_idx         on public.creative_clusters(owner_id);
create index if not exists chat_owner_thread_idx      on public.ai_chat_messages(owner_id, thread_id, created_at);

-- ============================================================
-- ROW LEVEL SECURITY — every row scoped to its owner
-- ============================================================
alter table public.brands               enable row level security;
alter table public.competitors          enable row level security;
alter table public.creators             enable row level security;
alter table public.content_assets       enable row level security;
alter table public.creative_dna_reports enable row level security;
alter table public.creative_clusters    enable row level security;
alter table public.ai_chat_messages     enable row level security;

-- Helper: same 4 policies repeated per table
do $$
declare
  t text;
begin
  for t in
    select unnest(array[
      'brands','competitors','creators','content_assets',
      'creative_dna_reports','creative_clusters','ai_chat_messages'
    ])
  loop
    execute format(
      'drop policy if exists "select_own" on public.%I; create policy "select_own" on public.%I for select using (auth.uid() = owner_id);', t, t
    );
    execute format(
      'drop policy if exists "insert_own" on public.%I; create policy "insert_own" on public.%I for insert with check (auth.uid() = owner_id);', t, t
    );
    execute format(
      'drop policy if exists "update_own" on public.%I; create policy "update_own" on public.%I for update using (auth.uid() = owner_id);', t, t
    );
    execute format(
      'drop policy if exists "delete_own" on public.%I; create policy "delete_own" on public.%I for delete using (auth.uid() = owner_id);', t, t
    );
  end loop;
end $$;

-- ============================================================
-- updated_at triggers
-- ============================================================
create or replace function public.set_updated_at() returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists brands_updated_at on public.brands;
create trigger brands_updated_at before update on public.brands
  for each row execute function public.set_updated_at();

drop trigger if exists assets_updated_at on public.content_assets;
create trigger assets_updated_at before update on public.content_assets
  for each row execute function public.set_updated_at();

drop trigger if exists clusters_updated_at on public.creative_clusters;
create trigger clusters_updated_at before update on public.creative_clusters
  for each row execute function public.set_updated_at();

-- ============================================================
-- STORAGE :: thumbnails bucket
-- ============================================================
insert into storage.buckets (id, name, public)
values ('thumbnails', 'thumbnails', true)
on conflict (id) do nothing;

-- Public read for thumbnails
drop policy if exists "public can read thumbnails" on storage.objects;
create policy "public can read thumbnails"
  on storage.objects for select
  using (bucket_id = 'thumbnails');

-- Authenticated upload to thumbnails
drop policy if exists "auth can upload thumbnails" on storage.objects;
create policy "auth can upload thumbnails"
  on storage.objects for insert
  with check (bucket_id = 'thumbnails' and auth.role() = 'authenticated');

-- Owners can delete their thumbnails (by path convention: <user_id>/...)
drop policy if exists "owner can delete thumbnails" on storage.objects;
create policy "owner can delete thumbnails"
  on storage.objects for delete
  using (bucket_id = 'thumbnails' and (auth.uid())::text = split_part(name, '/', 1));
